sudo: false
language: php

php:
  - 5.4
  - 5.5
  - 5.6

env:
  - VAULT_TOKEN=horde VAULT_ADDR=http://localhost:8200

before_script:
  - wget http://dl.fligl.io/vault.gz
  - gunzip vault.gz
  - chmod +x vault
  - mv vault /usr/sbin/vault

script:
    - ./vendor/bin/phpunit -v -c phpunit.xml

