sudo: false
language: php

php:
  - 5.4
  - 5.5
  - 5.6

env:
    - PATH=/home/travis/bin:$PATH VAULT_TOKEN=horde VAULT_ADDR=http://localhost:8200

before_script:
  - wget http://dl.fligl.io/vault.gz
  - gunzip vault.gz
  - chmod +x vault
  - mkdir -p /home/travis/bin
  - mv vault /home/travis/bin/vault

script:
  - composer up 
  - make test

